const globalNav = [
	{
		linkName: "Intersection Observer API",
		linkURL: "/js-funhouse/projects/intersectionObserver/index.html",
		shortDesc: "First play with the Intersection Observer API ",
		month: "12",
		year: "2021",
		tags: ["Intersection Observer API"],
	},
	{
		linkName: "DOM Manipulation",
		linkURL: "/js-funhouse/projects/dom-manipulation/index.html",
		month: "09",
		year: "2021",
		tags: ["DOM Manipulation", "append()", "appendChild()"],
	},
	{
		linkName: "Array Methods",
		linkURL: "/js-funhouse/projects/array-methods/index.html",
		month: "08",
		year: "2021",
		tags: [
			"array methods",
			"filter()",
			"find()",
			"forEach()",
			"some()",
			"every()",
			"reduce()",
			"includes()",
		],
	},
	{
		linkName: "Dark Mode Toggle Using Local Storage",
		linkURL: "/js-funhouse/projects/dark-mode-toggle/index.html",
		month: "07",
		year: "2021",
		tags: ["local storage", "dark mode", "getItem()", "setItem()"],
	},
	{
		linkName: "Shopping Cart Demo",
		linkURL: "/js-funhouse/projects/shopping-cart/index.html",
		month: "06",
		year: "2021",
		tags: ["e-commerce", "shopping cart"],
	},
	{
		linkName: "Web Component - Tooltip",
		linkURL: "/js-funhouse/projects/web-component-tooltip/index.html",
		month: "05",
		year: "2021",
		tags: ["web component", "shadowDOM"],
	},
	{
		linkName: "Object Entries",
		linkURL: "/js-funhouse/projects/object-entries/index.html",
		month: "05",
		year: "2021",
		tags: ["array methods", "Object.entries()"],
	},
];
export default globalNav;
