const globalNav = [
	// {
	// 	linkName: "SPA Router",
	// 	linkURL: "/js-funhouse/projects/spa-router/index.html",
	// 	desc: "Vanilla JS single page application router",
	// 	month: "12",
	// 	year: "2022",
	// 	tags: ["SPA"],
	// },
	{
		linkName: "Basic Counter using Lit Framework for Web Components",
		linkURL: "/js-funhouse/projects/lit-basic-counter/index.html",
		desc: "Using the Lit framework to create a basic counter",
		month: "06",
		year: "2022",
		tags: ["Lit", "Web Components"],
	},
	{
		linkName: "Preload Imagery With Progress Bars Using PreloadJS",
		linkURL: "/js-funhouse/projects/preloadjs/index.html",
		desc: "Use classes from the PreloadJS library to preload imagery and display progress bars",
		month: "06",
		year: "2022",
		tags: ["PreloadJS"],
	},
	{
		linkName: "Searching the Wikipedia API",
		linkURL: "/js-funhouse/projects/search-wikipedia-api/index.html",
		desc: "Using the fetch API to search the Wikipedia API and return endpoints into a card design",
		month: "04",
		year: "2022",
		tags: ["API", "fetch()", "search", "forms"],
	},
	{
		linkName: "Intersection Observer API",
		linkURL: "/js-funhouse/projects/intersectionObserver/index.html",
		desc: "First play with the Intersection Observer API, adding HTML components on-scroll ",
		month: "12",
		year: "2021",
		tags: ["Intersection Observer API"],
	},
	{
		linkName: "DOM Manipulation",
		linkURL: "/js-funhouse/projects/dom-manipulation/index.html",
		desc: "Methods to Add, change, remove DOM elements",
		month: "09",
		year: "2021",
		tags: ["DOM Manipulation", "append()", "appendChild()", "unfinished"],
	},
	{
		linkName: "Array Methods",
		linkURL: "/js-funhouse/projects/array-methods/index.html",
		desc: "7 of the most commonly used array methods",
		month: "08",
		year: "2021",
		tags: [
			"array methods",
			"filter()",
			"find()",
			"forEach()",
			"some()",
			"every()",
			"reduce()",
			"includes()",
		],
	},
	{
		linkName: "Dark Mode Toggle Using Local Storage",
		linkURL: "/js-funhouse/projects/dark-mode-toggle/index.html",
		desc: "Using local storage to persist a simple bolean state",
		month: "07",
		year: "2021",
		tags: ["local storage", "dark mode", "getItem()", "setItem()"],
	},
	{
		linkName: "Shopping Cart Demo",
		linkURL: "/js-funhouse/projects/shopping-cart/index.html",
		desc: "Basic prototype of adding products to a cart; combining several functions to add and delete DOM elements",
		month: "06",
		year: "2021",
		tags: ["e-commerce", "shopping cart", "unfinished"],
	},
	{
		linkName: "Web Component - Tooltip",
		linkURL: "/js-funhouse/projects/web-component-tooltip/index.html",
		desc: "Creating a re-usable Tooltip using Web Component API; component receives in unique text using props",
		month: "05",
		year: "2021",
		tags: ["web component", "shadowDOM", "props"],
	},
	{
		linkName: "Object Entries",
		linkURL: "/js-funhouse/projects/object-entries/index.html",
		desc: "Looping through an object with nested objects and mapping the key / value pairs to a HTML component",
		month: "05",
		year: "2021",
		tags: ["array methods", "Object.entries()"],
	},
];
export default globalNav;
