const productsObj = [
	{
		title: "Blue Ridge Mountain",
		url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail01.jpg",
		alt: "Golden Eagle flies over Blue Ridge Mountain",
		desc: "Georgia Golden Eagle soars through the valley",
		price: 89.72,
	},
	{
		title: "Aerial Blue",
		url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail02.jpg",
		alt: "Blue Ridge Mountains",
		desc: "The beautiful blue hues vibrate across the distance. Can you spot the Golden Eagle?",
		price: 85.39,
	},
	{
		title: "Southern Terminus",
		url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail03.jpg",
		alt: "Beginning of the Appalacian Trail",
		desc: "The Appalachian Trail runs from Georgia to Maine",
		price: 45.52,
	},
	{
		title: "Shapes Mirror",
		url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail04.jpg",
		alt: "Clouds and mountains",
		desc: "Mountainous clouds have an other-world symmetry with the mountains",
		price: 45.99,
	},
	// {
	// 	title: "Photo 05",
	// 	url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail05.jpg",
	// 	alt: "Falcon flies over Chattahoochee",
	// 	desc: "5 Product image caption Pic taken on Appalachian trail 2020",
	// 	price: 45.5,
	// 	landscape: false,
	// },
	// {
	// 	title: "Photo 06",
	// 	url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail06.jpg",
	// 	alt: "Falcon flies over Chattahoochee",
	// 	desc: "6 Product image caption Pic taken on Appalachian trail 2020",
	// 	price: 45.5,
	// 	landscape: false,
	// },
	// {
	// 	title: "Photo 07",
	// 	url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail07.jpg",
	// 	alt: "Falcon flies over Chattahoochee",
	// 	desc: "7 Product image caption Pic taken on Appalachian trail 2020",
	// 	price: 45.5,
	// 	landscape: false,
	// },
	// {
	// 	title: "Photo 08",
	// 	url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail08.jpg",
	// 	alt: "Falcon flies over Chattahoochee",
	// 	desc: "8 Product image caption Pic taken on Appalachian trail 2020",
	// 	price: 45.5,
	// 	landscape: false,
	// },
	// {
	// 	title: "Photo 09",
	// 	url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail09.jpg",
	// 	alt: "Falcon flies over Chattahoochee",
	// 	desc: "9 Product image caption Pic taken on Appalachian trail 2020",
	// 	price: 45.5,
	// },
	{
		title: "Rise",
		url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail10.jpg",
		alt: "Mist rises from the mountains",
		desc: "Mist rises from the vast forest",
		price: 45.5,
	},
	{
		title: "Rise & Rise",
		url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail11.jpg",
		alt: "Mist rises from the mountains",
		desc: "The mist rising creates dramatic views",
		price: 45.5,
	},
];
export default productsObj;
