const productsObj = [
	{
		title: "Photo 01",
		url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail01.jpg",
		alt: "Falcon flies over Chattahoochee",
		desc: "1 Product image caption Pic taken on Appalachian trail 2020",
		price: 89.72,
	},
	{
		title: "Photo 02",
		url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail02.jpg",
		alt: "Falcon flies over Chattahoochee",
		desc: "2 Product image caption Pic taken on Appalachian trail 2020",
		price: 85.39,
	},
	{
		title: "Photo 03",
		url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail03.jpg",
		alt: "Falcon flies over Chattahoochee",
		desc: "3 Product image caption Pic taken on Appalachian trail 2020",
		price: 45.5,
	},
	{
		title: "Photo 04",
		url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail04.jpg",
		alt: "Falcon flies over Chattahoochee",
		desc: "4 Product image caption Pic taken on Appalachian trail 2020",
		price: 45.5,
	},
	// {
	// 	title: "Photo 05",
	// 	url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail05.jpg",
	// 	alt: "Falcon flies over Chattahoochee",
	// 	desc: "5 Product image caption Pic taken on Appalachian trail 2020",
	// 	price: 45.5,
	// 	landscape: false,
	// },
	// {
	// 	title: "Photo 06",
	// 	url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail06.jpg",
	// 	alt: "Falcon flies over Chattahoochee",
	// 	desc: "6 Product image caption Pic taken on Appalachian trail 2020",
	// 	price: 45.5,
	// 	landscape: false,
	// },
	// {
	// 	title: "Photo 07",
	// 	url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail07.jpg",
	// 	alt: "Falcon flies over Chattahoochee",
	// 	desc: "7 Product image caption Pic taken on Appalachian trail 2020",
	// 	price: 45.5,
	// 	landscape: false,
	// },
	// {
	// 	title: "Photo 08",
	// 	url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail08.jpg",
	// 	alt: "Falcon flies over Chattahoochee",
	// 	desc: "8 Product image caption Pic taken on Appalachian trail 2020",
	// 	price: 45.5,
	// 	landscape: false,
	// },
	// {
	// 	title: "Photo 09",
	// 	url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail09.jpg",
	// 	alt: "Falcon flies over Chattahoochee",
	// 	desc: "9 Product image caption Pic taken on Appalachian trail 2020",
	// 	price: 45.5,
	// },
	{
		title: "Photo 10",
		url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail10.jpg",
		alt: "Falcon flies over Chattahoochee",
		desc: "10 Product image caption Pic taken on Appalachian trail 2020",
		price: 45.5,
	},
	{
		title: "Photo 11",
		url: "https://shopping-cart-demo-2021-06.s3.amazonaws.com/chattahoochee-trail11.jpg",
		alt: "Falcon flies over Chattahoochee",
		desc: "11 Product image caption Pic taken on Appalachian trail 2020",
		price: 45.5,
	},
];
export default productsObj;
